# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documnetation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
vetor1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
vetor2 = np.array([vetor1, vetor1])

# Create a 3-dimensional Numpy array using np.array()
vetor3 = np.array([vetor2, vetor2, vetor2])

In [7]:
vetor3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
vetor1.shape, vetor1.ndim, vetor1.dtype, vetor1.size, type(vetor1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
vetor2.shape, vetor2.ndim, vetor2.dtype, vetor2.size, type(vetor2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
vetor3.shape, vetor3.ndim, vetor3.dtype, vetor3.size, type(vetor3)

((3, 2, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
quadro = pd.DataFrame(vetor2)
quadro

0  1  2
0  1  2  3
1  1  2  3

In [25]:
# Create an array of shape (10, 2) with only ones
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [223]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size = (7,2))

array([[7, 3],
       [8, 4],
       [8, 3],
       [9, 4],
       [8, 7],
       [2, 0],
       [2, 3]])

In [48]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))

array([[0.15450292, 0.39669815, 0.87662514, 0.80895666, 0.69739642],
       [0.44407224, 0.88818285, 0.95882615, 0.70879106, 0.07903146],
       [0.29516921, 0.86770829, 0.62570049, 0.23106594, 0.81429608]])

In [53]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(4, 6, size = (4, 6))

array([[4, 5, 4, 4, 4, 5],
       [4, 4, 4, 5, 4, 4],
       [4, 4, 5, 4, 5, 5],
       [5, 4, 5, 4, 5, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [59]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
cu = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
np.unique(cu)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [99]:
# Find the 0'th index of the latest array you created
cu

array([[5, 3, 1, 5, 7, 7, 9],
       [3, 7, 1, 4, 4, 5, 7],
       [7, 4, 7, 3, 6, 2, 9]])

In [92]:
cu.shape

(3, 7)

In [224]:
# Get the first 2 values of the first 2 rows of the latest array
np.array([cu[0][0:2], cu[1][0:2]])
cu[0:2, 0:2] #Melhor assim, porra!

array([[5, 3],
       [3, 7]])

In [131]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand = np.random.randint(0, 10, size = (3, 5))
um = np.ones(shape = (3,5))

In [132]:
# Add the two arrays together
rand + um

array([[ 1.,  1.,  3.,  2.,  5.],
       [10.,  6.,  7.,  4.,  7.],
       [ 8.,  1.,  6.,  8.,  5.]])

In [133]:
# Create another array of ones of shape (5, 3)
um2 = np.ones(shape = (5,3))

In [ ]:
# Try add the array of ones and the other most recent array together
um + um2

In [135]:
um2.reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [136]:
# Create another array of ones of shape (3, 5)
um3 = np.ones(shape = (3, 5))

In [138]:
# Subtract the new array of ones from the other most recent array
um - um3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [227]:
# Multiply the ones array with the latest array
um3*um

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
# Take the latest array to the power of 2 using '**'
um3**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [141]:
# Do the same thing with np.square()
np.square(um3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [142]:
# Find the mean of the latest array using np.mean()
np.mean(um)

1.0

In [143]:
# Find the maximum of the latest array using np.max()
np.max(um)

1.0

In [144]:
# Find the minimum of the latest array using np.min()
np.min(um)

1.0

In [145]:
# Find the standard deviation of the latest array
np.std(um)

0.0

In [146]:
# Find the variance of the latest array
np.var(um)

0.0

In [148]:
# Reshape the latest array to (3, 5, 1)
um.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [149]:
# Transpose the latest array
um.reshape(3, 5, 1).T

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

What does the transpose do?
It fucks your mom

In [153]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a = np.random.randint(10, size = (3, 3))
b = np.random.randint(10, size = (3, 2))

In [155]:
# Perform a dot product on the two newest arrays you created
np.dot(a, b)

array([[75, 23],
       [33, 16],
       [74, 45]])

In [156]:
np.dot(b, a)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [161]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
x, y = np.random.randint(10, size = (4, 3)), np.random.randint(10, size = (4, 3))

In [163]:
x

array([[7, 0, 7],
       [3, 0, 7],
       [3, 5, 7],
       [3, 2, 8]])

In [167]:
# Perform a dot product on the two newest arrays you created
np.dot(x, y.T)

array([[21, 42, 35,  0],
       [13, 38, 27,  0],
       [53, 43, 67, 15],
       [30, 45, 46,  6]])

In [168]:
np.dot(x.T, y)

array([[ 23,  92,  31],
       [ 10,  46,  15],
       [ 35, 143,  63]])

It doesn't work. How would you fix it? I fuck your mom

###### Take the latest two arrays, perform a transpose on one of them and then perform 
###### a dot product on them both
Already done it. You actually suck at linear algebra. And also does your mothers.

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [37]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [173]:
# Compare the two arrays with '>'
z, w = np.random.randint(10, size = (3, 3)), np.random.randint(10, size = (3, 3))

What happens when you compare the arrays with `>`?

In [178]:
# Compare the two arrays with '>='
np.array([z > w, w > z])

array([[[False, False,  True],
        [ True,  True, False],
        [False, False,  True]],

       [[ True,  True, False],
        [False, False, False],
        [ True,  True, False]]])

In [181]:
z

array([[4, 3, 7],
       [7, 6, 2],
       [0, 0, 2]])

In [182]:
# Find which elements of the first array are greater than 7
z[z>3]

array([4, 7, 7, 6])

In [185]:
# Which parts of each array are equal? (try using '==')
z == w

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [197]:
z[z == w]

array([2])

In [186]:
# Sort one of the arrays you just created in ascending order
np.sort(z)

array([[3, 4, 7],
       [2, 6, 7],
       [0, 0, 2]])

In [187]:
# Sort the indexes of one of the arrays you just created
np.argsort(z)

array([[1, 0, 2],
       [2, 1, 0],
       [0, 1, 2]])

In [201]:
# Find the index with the maximum value in one of the arrays you've created
np.where(np.max(z)), np.max(z)

((array([0]),), 7)

In [192]:
z

array([[4, 3, 7],
       [7, 6, 2],
       [0, 0, 2]])

In [202]:
# Find the index with the minimum value in one of the arrays you've created
np.min(z)

0

In [209]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.max(z, axis = 0)

array([7, 6, 7])

In [207]:
z

array([[4, 3, 7],
       [7, 6, 2],
       [0, 0, 2]])

In [210]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.min(z, axis = 1)

array([3, 2, 0])

In [212]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([-1.5437254 ,  1.11689344, -1.15551591,  1.57011062, -1.12495174,
        1.28192038, -0.02842146, -1.71642445, -1.04296139,  1.32647167])

In [222]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [232]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.