In [1]:
import numpy as np
import pandas as pd

# Arrays

In [2]:
ar = np.array([1, 2])

In [3]:
ar

array([1, 2])

In [4]:
ar2 = np.array([[1,2,4],[1,4,5]])

In [5]:
ar2

array([[1, 2, 4],
       [1, 4, 5]])

In [6]:
ar3 = np.array([[[1,2,3],[3,4,5],[5,6,7]], 
                [[1,2,3],[3,4,5],[5,6,7]],
               [[1,2,3],[3,4,5],[5,6,7]]])

In [7]:
ar3

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [8]:
ar.dtype

dtype('int64')

In [9]:
type(ar), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
ar4 = np.array([[[[ar3, ar3, ar3, ar3], [ar3, ar3,ar3, ar3]], [[ar3, ar3,ar3, ar3], [ar3, ar3,ar3, ar3]]], [[[ar3, ar3,ar3, ar3], [ar3, ar3,ar3, ar3]], [[ar3, ar3,ar3, ar3], [ar3, ar3,ar3, ar3]]]])

In [11]:
ar4

array([[[[[[[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]]],


          [[[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]]],


          [[[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]]],


          [[[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]]]],



         [[[[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]],

           [[1, 2, 3],
            [3, 4, 5],
            [5, 6, 7]

In [12]:
ar.shape, ar2.shape, ar3.shape, ar4.shape

((2,), (2, 3), (3, 3, 3), (2, 2, 2, 4, 3, 3, 3))

In [13]:
ar.ndim, ar2.ndim, ar3.ndim, ar4.ndim

(1, 2, 3, 7)

In [14]:
ar.size, ar2.size, ar3.size, ar4.size

(2, 6, 27, 864)

In [15]:
ar5 = np.array([[ar4], [ar4]])

In [16]:
pd.DataFrame(ar2)

0  1  2
0  1  2  4
1  1  4  5

# Criando Arrays

### Completando com 1:

In [37]:
um = np.ones((1, 2, 2)) #Dá pra fazer com zeros também.

In [38]:
um

array([[[1., 1.],
        [1., 1.]]])

In [39]:
um.size, um.ndim

(4, 3)

### Povoando com números aleatórios:

In [40]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
np.random.randint(0, 50, size = (2, 2, 3))

array([[[26, 21, 27],
        [13, 10, 14]],

       [[ 1, 22, 10],
        [ 3,  0, 28]]])

In [ ]:
matriz = np.random.random((3,4))

In [155]:
matriz

array([[0.82868133, 0.04689632, 0.62628715, 0.54758616],
       [0.819287  , 0.19894754, 0.8568503 , 0.35165264],
       [0.75464769, 0.29596171, 0.88393648, 0.32551164]])

In [133]:
rand = np.random.seed(seed = 10)

In [144]:
a, b = np.random.randint(100), np.random.randint(100)
a, b

(49, 51)

# Enxergando Arrays e Matrizes

In [173]:
a = np.random.randint(10, size = 10)

In [174]:
a

array([8, 6, 6, 5, 6, 0, 0, 6, 9, 1])

In [175]:
np.unique(a)

array([0, 1, 5, 6, 8, 9])

In [176]:
a.min()

0

In [177]:
matriz.min(), matriz[1].min()

(0.04689631938924976, 0.1989475396788123)

In [178]:
matriz, matriz[1:3, 1:3],

(array([[0.82868133, 0.04689632, 0.62628715, 0.54758616],
        [0.819287  , 0.19894754, 0.8568503 , 0.35165264],
        [0.75464769, 0.29596171, 0.88393648, 0.32551164]]),
 array([[0.19894754, 0.8568503 ],
        [0.29596171, 0.88393648]]))

$x=\frac{10}{2}$

Eu não sei como surgiu a linha "Type Markdown and LaTeX: 𝛼2". Mas fez eu me dar conta de que posso usar alguns comandos LateX aqui dentro, o que é foda.

In [183]:
ar3

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [550]:
ar3[1][0][1:3]

array([2, 3])

In [210]:
cu = pd.DataFrame({'A': range(10), 'B': range(20,30)})

In [211]:
cu

A   B
0  0  20
1  1  21
2  2  22
3  3  23
4  4  24
5  5  25
6  6  26
7  7  27
8  8  28
9  9  29

In [215]:
np.array(cu), np.array(cu)[1]

(array([[ 0, 20],
        [ 1, 21],
        [ 2, 22],
        [ 3, 23],
        [ 4, 24],
        [ 5, 25],
        [ 6, 26],
        [ 7, 27],
        [ 8, 28],
        [ 9, 29]]), array([ 1, 21]))

# Manipulando Arrays

In [218]:
a = np.array([1, 3, 4])

In [219]:
a

array([1, 3, 4])

In [225]:
b = np.ones(3)*2

In [226]:
b

array([2., 2., 2.])

In [232]:
a-b, abs(a-b)

(array([-1.,  1.,  2.]), array([1., 1., 2.]))

In [237]:
a*ar3

array([[[ 1,  6, 12],
        [ 3, 12, 20],
        [ 5, 18, 28]],

       [[ 1,  6, 12],
        [ 3, 12, 20],
        [ 5, 18, 28]],

       [[ 1,  6, 12],
        [ 3, 12, 20],
        [ 5, 18, 28]]])

In [322]:
matriz1 = np.array([[5, 6, 7], [7, 8, 9], [10, 11, 12]])

In [323]:
matriz1

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [10, 11, 12]])

In [324]:
matriz2 = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]                              
                   ]) 

In [325]:
matriz2

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [326]:
matriz1.shape, matriz2.shape

((3, 3), (3, 3))

#### Multiplicar usando * não é o mesmo que multiplicação matricial!

In [327]:
matriz1*matriz2

array([[ 5, 12, 21],
       [21, 32, 45],
       [60, 77, 96]])

#### Esse tipo de multiplicação é comutativo.


In [328]:
matriz2*matriz1

array([[ 5, 12, 21],
       [21, 32, 45],
       [60, 77, 96]])

### Multiplicação matricial é feito por meio de dot:

In [329]:
np.dot(matriz1, matriz2)

array([[ 65,  83, 101],
       [ 85, 109, 133],
       [115, 148, 181]])

In [330]:
np.dot(matriz2, matriz1)

array([[ 49,  55,  61],
       [ 93, 105, 117],
       [159, 180, 201]])

In [344]:
ar = np.array([[1], [2], [3]])
ar1 = np.array([1, 2, 3])

In [345]:
ar, ar1

(array([[1],
        [2],
        [3]]), array([1, 2, 3]))

In [346]:
ar.shape, ar1.shape

((3, 1), (3,))

In [347]:
np.dot(ar1, matriz1)

array([49, 55, 61])

In [349]:
np.dot(matriz1, ar)

array([[38],
       [50],
       [68]])

# Reshape e Transposto

In [361]:
a.shape

(3,)

In [360]:
a

array([1, 3, 4])

### Mudando o formato do array:

#### Mantendo a mesma informação!

In [370]:
a.reshape(3,1)

array([[1],
       [3],
       [4]])

In [372]:
a.reshape(3,1,1)

array([[[1]],

       [[3]],

       [[4]]])

In [379]:
a.reshape(3,2) #Não funciona, porque não tem informação o suficiente

ValueError: cannot reshape array of size 3 into shape (3,2)

In [380]:
a.reshape(1,3)

array([[1, 3, 4]])

### Transposto

In [391]:
ar3, ar3.shape

(array([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]],
 
        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]],
 
        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]]), (3, 3, 3))

In [392]:
ar3.T, ar3.T.shape

(array([[[1, 1, 1],
         [3, 3, 3],
         [5, 5, 5]],
 
        [[2, 2, 2],
         [4, 4, 4],
         [6, 6, 6]],
 
        [[3, 3, 3],
         [5, 5, 5],
         [7, 7, 7]]]), (3, 3, 3))

In [393]:
ar2, ar2.shape

(array([[1, 2, 4],
        [1, 4, 5]]), (2, 3))

In [394]:
ar2.T, ar2.T.shape

(array([[1, 1],
        [2, 4],
        [4, 5]]), (3, 2))

In [396]:
a

array([1, 3, 4])

In [402]:
ar*ar3

array([[[ 1,  2,  3],
        [ 6,  8, 10],
        [15, 18, 21]],

       [[ 1,  2,  3],
        [ 6,  8, 10],
        [15, 18, 21]],

       [[ 1,  2,  3],
        [ 6,  8, 10],
        [15, 18, 21]]])

In [403]:
ar3

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [404]:
ar

array([[1],
       [2],
       [3]])

### Exemplo de multiplicação matricial na vida real

In [417]:
vendas = pd.DataFrame({'Almond butter': [2, 9, 11, 13, 15], 'Peanut butter': [7, 4, 14, 13, 18], 'Cashew butter': [1, 16, 18, 16, 9]}, index = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'])

In [418]:
vendas

Almond butter  Peanut butter  Cashew butter
Mon                2              7              1
Tues               9              4             16
Wed               11             14             18
Thurs             13             13             16
Fri               15             18              9

In [425]:
precos = pd.DataFrame({'Almond butter': [10], 'Peanut butter': [8], 'Cashew butter': [12]}, index = ['Preço'])

In [426]:
precos

Almond butter  Peanut butter  Cashew butter
Preço             10              8             12

In [427]:
matriz_vendas = np.array(vendas)  

In [428]:
matriz_vendas

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [429]:
vetor_precos = np.array(precos)

In [434]:
vetor_precos

array([[10,  8, 12]])

In [435]:
vetor_precos.shape

(1, 3)

In [436]:
matriz_vendas.shape

(5, 3)

In [438]:
vetor_total = np.dot( matriz_vendas, vetor_precos.T)

In [486]:
vetor_total

array([[ 88],
       [314],
       [438],
       [426],
       [402]])

In [487]:
vendas['Total'] = vetor_total

In [488]:
vendas

Almond butter  Peanut butter  Cashew butter  Total
Mon                2              7              1     88
Tues               9              4             16    314
Wed               11             14             18    438
Thurs             13             13             16    426
Fri               15             18              9    402

### Ordenando Arrays

In [492]:
np.sort(matriz_vendas)

array([[ 1,  2,  7],
       [ 4,  9, 16],
       [11, 14, 18],
       [13, 13, 16],
       [ 9, 15, 18]])

In [493]:
np.sort(vendas)

array([[  1,   2,   7,  88],
       [  4,   9,  16, 314],
       [ 11,  14,  18, 438],
       [ 13,  13,  16, 426],
       [  9,  15,  18, 402]])

In [499]:
cu = np.array([3,7,1])

In [500]:
np.argsort(cu)

array([2, 0, 1])

In [511]:
np.argmin(cu)

3

In [517]:
cu = np.array([[[2, 2]], [[2, 1]]])

In [518]:
cu.shape

(2, 1, 2)

In [524]:
np.argmin(cu, axis = 0)

array([[0, 1]])

# Exemplo Prático: IMAGENS como arrays

Para carregar a imagem, tem que estar na forma de MarkDown! <#img src = 'blablabla'> (Tira o #)

<img src = 'feijao'>

In [530]:
from matplotlib.image import imread

In [535]:
feijao = imread('feijao.png')

In [539]:
type(feijao)

numpy.ndarray

In [541]:
feijao.size, feijao.shape, feijao.ndim

(552960, (360, 512, 3), 3)

In [543]:
feijao.dtype


dtype('float32')

In [547]:
feijao[0][0][0]

1.0